name: Fetch Latest Release from dw-cli

on:
  push:
    branches:
    - murex/scripts

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest release
        id: latest_release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: 'dashwave',
              repo: 'dw-cli'
            });
            const latest_release = releases.data[0];
            console.log(`Latest release is: ${latest_release.name}`);
            return latest_release;

      - name: Create a release
        uses: actions/create-release@v1
        with:
          github-token: ${{ secrets.PAT }}
          tag_name: ${{ steps.latest_release.outputs.result.tag_name }}
          release_name: ${{ steps.latest_release.outputs.result.name }}
          body: ${{ steps.latest_release.outputs.result.body }}
          draft: false
          prerelease: false
